#!/usr/bin/env python3
"""Rebuild the embedded coastline data in sea_mile/tui/coastlines.py.

Downloads Natural Earth 110m coastline shapefile, extracts and quantizes
coordinates to 1 decimal place, then gzip+base64 compresses the result.
Requires: pyshp (``uv pip install pyshp``).

Usage::

    uv run scripts/build_coastline.py
"""

from __future__ import annotations

import base64
import gzip
import hashlib
import io
import json
import tempfile
import zipfile
from pathlib import Path
from urllib.request import urlopen

NE_URL = "https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip"
NE_SHA256 = "664449b39070027e882abb295974d182afec18ca21107273d17e9e8bf6f64817"
NE_MAX_BYTES = 2 * 1024 * 1024
NE_REQUIRED_FILES = (
    "ne_110m_coastline.dbf",
    "ne_110m_coastline.shp",
    "ne_110m_coastline.shx",
)
TARGET = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "sea_mile"
    / "tui"
    / "coastlines.py"
)
PRECISION = 1  # decimal places (~1.1 km)


def download_shapefile() -> bytes:
    print(f"Downloading {NE_URL} ...")
    if not NE_URL.startswith("https://"):
        raise ValueError("Natural Earth URL must use HTTPS")
    # The only permitted value is the constant HTTPS URL checked above.
    with urlopen(NE_URL, timeout=30) as resp:  # nosec B310
        declared = resp.headers.get("Content-Length")
        if declared is not None and int(declared) > NE_MAX_BYTES:
            raise ValueError("Natural Earth archive exceeds the download limit")
        data = resp.read(NE_MAX_BYTES + 1)
    if len(data) > NE_MAX_BYTES:
        raise ValueError("Natural Earth archive exceeds the download limit")
    if hashlib.sha256(data).hexdigest() != NE_SHA256:
        raise ValueError("Natural Earth archive checksum does not match")
    return data


def _required_archive_members(data: bytes) -> dict[str, bytes]:
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        names = set(archive.namelist())
        missing = set(NE_REQUIRED_FILES) - names
        if missing:
            raise ValueError(
                "Natural Earth archive is missing: " + ", ".join(sorted(missing))
            )
        return {name: archive.read(name) for name in NE_REQUIRED_FILES}


def extract_coastline(data: bytes) -> list[list[tuple[float, float]]]:
    import shapefile  # type: ignore[import-not-found]

    with tempfile.TemporaryDirectory() as tmp:
        for name, content in _required_archive_members(data).items():
            (Path(tmp) / name).write_bytes(content)
        shp_path = Path(tmp) / "ne_110m_coastline.shp"
        sf = shapefile.Reader(str(shp_path))
        features: list[list[tuple[float, float]]] = []
        for sr in sf.iterShapeRecords():
            pts = [
                (round(x, PRECISION), round(y, PRECISION)) for x, y in sr.shape.points
            ]
            features.append(pts)
        return features


def encode(features: list[list[tuple[float, float]]]) -> str:
    raw = json.dumps(features).encode()
    compressed = gzip.compress(raw, compresslevel=9)
    return base64.b64encode(compressed).decode()


def write_module(b64: str, n_features: int, n_points: int) -> None:
    content = f'''\
"""Embedded Natural Earth 110m coastline data.

Source: naturalearthdata.com/downloads/110m-physical-vectors/110m-coastline/
License: Public Domain / CC0
Coordinates: {PRECISION} decimal place(s) (~{1.1:.1f} km resolution)
Generated by: scripts/build_coastline.py
Features: {n_features}, Total points: {n_points}
"""

from __future__ import annotations

import base64
import gzip
import json
from typing import Final

_COASTLINE_B64: Final[str] = \\
    "{b64}"

_COASTLINE_CACHE: list[list[list[float]]] | None = None


def load_coastlines() -> list[list[list[float]]]:
    """Decode and cache the embedded coastline polylines.

    Returns a list of polyline segments, where each segment is a list of
    [longitude, latitude] coordinate pairs.
    """
    global _COASTLINE_CACHE  # noqa: PLW0603
    if _COASTLINE_CACHE is None:
        raw = gzip.decompress(base64.b64decode(_COASTLINE_B64))
        _COASTLINE_CACHE = json.loads(raw)
    return _COASTLINE_CACHE
'''
    TARGET.write_text(content)
    print(f"Written {TARGET} ({len(content)} bytes)")


def main() -> None:
    data = download_shapefile()
    features = extract_coastline(data)
    n_points = sum(len(f) for f in features)
    b64 = encode(features)
    write_module(b64, len(features), n_points)
    print(f"Done: {len(features)} features, {n_points} points, {len(b64)} base64 chars")


if __name__ == "__main__":
    main()
