#!/usr/bin/env python3
"""Rebuild the embedded coastline data in sea_mile/tui/coastlines.py.

Downloads Natural Earth 110m coastline shapefile, extracts and quantizes
coordinates to 1 decimal place, then gzip+base64 compresses the result.
Requires: pyshp (``uv pip install pyshp``).

Usage::

    uv run scripts/build_coastline.py
"""

from __future__ import annotations

import base64
import gzip
import io
import json
import tempfile
import zipfile
from pathlib import Path
from urllib.request import urlopen

NE_URL = "https://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip"
TARGET = (
    Path(__file__).resolve().parent.parent
    / "src"
    / "sea_mile"
    / "tui"
    / "coastlines.py"
)
PRECISION = 1  # decimal places (~1.1 km)


def download_shapefile() -> bytes:
    print(f"Downloading {NE_URL} ...")
    with urlopen(NE_URL, timeout=30) as resp:  # noqa: S310
        return resp.read()


def extract_coastline(data: bytes) -> list[list[tuple[float, float]]]:
    import shapefile  # type: ignore[import-untyped]

    with tempfile.TemporaryDirectory() as tmp:
        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            zf.extractall(tmp)
        shp_path = list(Path(tmp).glob("*.shp"))[0]
        sf = shapefile.Reader(str(shp_path))
        features: list[list[tuple[float, float]]] = []
        for sr in sf.iterShapeRecords():
            pts = [
                (round(x, PRECISION), round(y, PRECISION)) for x, y in sr.shape.points
            ]
            features.append(pts)
        return features


def encode(features: list[list[tuple[float, float]]]) -> str:
    raw = json.dumps(features).encode()
    compressed = gzip.compress(raw, compresslevel=9)
    return base64.b64encode(compressed).decode()


def write_module(b64: str, n_features: int, n_points: int) -> None:
    content = f'''\
"""Embedded Natural Earth 110m coastline data.

Source: naturalearthdata.com/downloads/110m-physical-vectors/110m-coastline/
License: Public Domain / CC0
Coordinates: {PRECISION} decimal place(s) (~{1.1:.1f} km resolution)
Generated by: scripts/build_coastline.py
Features: {n_features}, Total points: {n_points}
"""

from __future__ import annotations

import base64
import gzip
import json
from typing import Final

_COASTLINE_B64: Final[str] = \\
    "{b64}"

_COASTLINE_CACHE: list[list[list[float]]] | None = None


def load_coastlines() -> list[list[list[float]]]:
    """Decode and cache the embedded coastline polylines.

    Returns a list of polyline segments, where each segment is a list of
    [longitude, latitude] coordinate pairs.
    """
    global _COASTLINE_CACHE  # noqa: PLW0603
    if _COASTLINE_CACHE is None:
        raw = gzip.decompress(base64.b64decode(_COASTLINE_B64))
        _COASTLINE_CACHE = json.loads(raw)
    return _COASTLINE_CACHE
'''
    TARGET.write_text(content)
    print(f"Written {TARGET} ({len(content)} bytes)")


def main() -> None:
    data = download_shapefile()
    features = extract_coastline(data)
    n_points = sum(len(f) for f in features)
    b64 = encode(features)
    write_module(b64, len(features), n_points)
    print(f"Done: {len(features)} features, {n_points} points, {len(b64)} base64 chars")


if __name__ == "__main__":
    main()
